class OutputHeaders
  # order of key values matters!
  ROW_FIELDS = {'Clerk ID' => '',
                'Customer' => '',
                'Parser' => '',
                'File Name' => '',
                'Invoice Number' => '',
                'Deduction Post Date' => '',
                'Promo Start Date' => '',
                'Promo End Date' => '',
                'Deduction Category' => '',
                'Deduction Account' => '',
                'Deduction Type' => '',
                'Retail Chain Name' => '',
                'Planning Retailer' => '',
                'Customer Chain ID' => '',
                'Customer Detailed Name' => '',
                'Chargeback Amount' => '',
                'Customer Number' => '',
                'Customer Location' => '',
                'Customer City' => '',
                'Customer State' => '',
                'Brand' => '',
                'Product' => '',
                'Unit' => '',
                'Description' => '',
                'Invoice' => '',
                'Ordered' => '',
                'Shipped' => '',
                'Whlse' => '',
                'Total Discount%' => '',
                'MCB%' => '',
                'TOL User' => '',
                'UPC' => '',
                'Reference Number' => '',
                'Reference Date' => '',
                'KeHE Comment' => '',
                'EP Fee' => '',
                'Variable Rate Per Unit' => ''
              }.freeze
end
