class OutputHeaders
  # order of key values matters!
  ROW_FIELDS = {'Customer' => '',
                'Parser' => '',
                'File Name' => '',
                'Invoice Number' => '',
                'Deduction Post Date' => '',
                'Promo Start Date' => '',
                'Promo End Date' => '',
                'Deduction Type' => '',
                'Deduction Description' => '',
                'Customer Chain ID' => '',
                'Customer Detailed Name' => '',
                'Chargeback Amount' => '',
                'Customer Number' => '',
                'Customer Location' => '',
                'Customer City' => '',
                'Customer State' => '',
                'Brand' => '',
                'Product' => '',
                'Unit' => '',
                'Description' => '',
                'Invoice' => '',
                'Ordered' => '',
                'Shipped' => '',
                'Whlse' => '',
                'Total Discount%' => '',
                'MCB%' => '',
                'TOL User' => '',
                'UPC' => '',
                'Reference Number' => '',
                'Reference Date' => '',
                'KEHE Comment' => '',
                'EXT-COST' => '',
                'EP Fee' => ''
              }
end
