default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: clerk_ocr_dev

test:
  <<: *default
  database: clerk_ocr_test

production:
  <<: *default
  database: clerk_ocr_prod
