module Mappers
  module Helpers
    module GlobalLookups
      module PlanningRetailerLookup
        PLANNING_RETAILER_LOOKUP = [
          {"Retail Chain Name"=>"Adams Fairacre Farm", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Ada's Natural Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Ahold / Stop & Shop", "Planning Retailer"=>"Ahold / Stop & Shop"},
          {"Retail Chain Name"=>"Akins Natural Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Alameda Natural Grocery", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Alexanders", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Alfalfas", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Apple Tree Natural Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Atkinson Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Balducci's", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Bales Marketplace", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Ballard Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Barons Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Bashas", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Basic Food Ltd", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Beacon Natural Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Berkeley Bowl", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Berryvale Grocery", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Better Health", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"BIG Y", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Blossom on Lopez, Inc.", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Boney's Bayside Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Bristol Farms", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Brookshire Grocery", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Broulms", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"CA Independent Natural Grocers", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"California Organics", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Calvert Retail", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Cannatas Family Mkt", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Cardiff Seaside Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Carnival Finer Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Cashwise", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Central Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Chamberlin's Marketplace", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Chucks Produce", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Cids Food Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Clark's Nutrition Center", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Coborns", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Community Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Coos Head Food Co-op", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Country Aire Grocery", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Country Sun", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Country Village Nutrition", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"County Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Crest Discount Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Dahlia & Sage Community Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Danimaxx", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Davenport Farms", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Dawson's Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Deans Natural Food Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Decicco Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Deland Bakery & Natural Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Dierbergs", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Dixie Nutrition", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Dover Natural Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Draeger's", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Drivers Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Duckweed Urban Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Earth Fare", "Planning Retailer"=>"Earth Fare"},
          {"Retail Chain Name"=>"Earth Origins", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"East Village Organic", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Edwards Market LLC", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Elm Health", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Erewhon", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Eureka Natural Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Everman Natural Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Fairfax IGA Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Fairway", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Farmer Joe`s", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Feel-Rite", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Fit-Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Foodworks II", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"For Goodness Sake", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Fountain City Health Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Four Seasons Market LLC", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Frazier Farms", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Fresh & Natural", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Fresh Thyme", "Planning Retailer"=>"Fresh Thyme"},
          {"Retail Chain Name"=>"Garden Gourmet Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Garden Home Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Garden of Light", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Gateway Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Gelson's Markets", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Giant Eagle", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Giunta's Meat Farms", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Good Food Store", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Good Shepherd Health", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Granite State Natural Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Grassroots Natural Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Graul's Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Green Acres", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Green Zebra Grocery", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Grosvenor Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Haight Street Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Harmon's", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Harvest Health", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Harvest Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Health Food Center", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Health Hut", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Health Nuts", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Healthway of Southern NE", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Healthy Foods Plus", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Healthy Living", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"HEB", "Planning Retailer"=>"HEB"},
          {"Retail Chain Name"=>"Hendersonville Produce", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"HI Independent Natural Grocers", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Hollywood Supermarket", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Homeland", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Honest Green Market LLC", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"HSU & Co", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"INFRA", "Planning Retailer"=>"INFRA"},
          {"Retail Chain Name"=>"Island Naturals", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Janssen's Market LLC", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Jericho Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Jimbos", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Johnson Compounding Center", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Just Local Food Coop", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"KeHE", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Ken's Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Kettle and Fire, Inc.", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Key Food", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Kings Super Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Kowalski", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Kroger", "Planning Retailer"=>"Kroger"},
          {"Retail Chain Name"=>"LA Independent Natural Grocers", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Lambs Fresh Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Lassen's", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Lazy Acres", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Lifesource Natural Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"LMK Grocery", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Locale Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Love Whole Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Manzanita Fresh Food", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Mardi Gras Zone", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Market of Choice", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Marketplace Natural", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Marlene's", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Marlin Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Meijer", "Planning Retailer"=>"Meijer"},
          {"Retail Chain Name"=>"Merchant Distributors, Inc.", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Meyers Falls Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"MILLER'S NATURAL FOODS", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Mission Nutrition", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Mississippi Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Missoula Fresh Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Mollie Stones", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Morton William", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Mother's Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Mountain Valley Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Mt. Hope", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Murphy's", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Mustard Seed", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Native Sun", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Natural Food Plus", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Natural Frontier", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Natural Grocers (NGVC)", "Planning Retailer"=>"Natural Grocers (NGVC)"},
          {"Retail Chain Name"=>"Natural Living Center", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Natural Pantry Dry", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Natural Way Health Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Nature's Goods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Nature's Green Grocer", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"NCG", "Planning Retailer"=>"NCG"},
          {"Retail Chain Name"=>"New Bridge Organic Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"New Earth Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"New Leaf", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"New Moon Natural Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"New Seasons Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Newport Avenue Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"NM Independent Natural Grocers", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Nori's Village Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Nugget Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Olivers Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Olympia Health Food Center", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"OR Independent Natural Grocers", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Oregon Natural Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Organic Basic Food", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Organica", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Palace Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Palisades Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Park Slop Co-op", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Pats Marketplace", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Piazza's Fine Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Pilgrms Nutrition", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Plum Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Polson's", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Publix", "Planning Retailer"=>"Publix"},
          {"Retail Chain Name"=>"Rainbow Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Raisin Rack", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Raleys", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Reasors", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"River Wards LLC", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Rollin' Oats Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Roths Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Roundy's", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Roxy's", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Royal Blue Grocery", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Safeway / Albertsons", "Planning Retailer"=>"Safeway / Albertsons"},
          {"Retail Chain Name"=>"Samples - UNFI", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Sebastopol Community Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Seven Grains Natural", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Sherms", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Shop-N-Kart", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Skogens", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"SOHO Organic Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Southtown Health Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"SPD Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Spice n Nice", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Sprouts", "Planning Retailer"=>"Sprouts"},
          {"Retail Chain Name"=>"Staff of Life", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Streets Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Sunflower Shoppe", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Sunshine Health Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Super 1 Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Sweet Clover Market, Llc", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Tailor Made Nutrition", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Tapps Supermarket", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"The Fresh Market", "Planning Retailer"=>"The Fresh Market"},
          {"Retail Chain Name"=>"The Store", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Thriftway", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Ticonderoga Natural Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Town & Country Markets", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"UNFI East", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"UNFI West", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"URM", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Village Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Vitality & Health", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Vitamins Plus", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"WA Independent Natural Grocers", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Wakefern", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Wards Supermarket", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Wealth of Health", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Wegmans", "Planning Retailer"=>"Wegmans"},
          {"Retail Chain Name"=>"Western Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Westside Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Whole Foods", "Planning Retailer"=>"Whole Foods"},
          {"Retail Chain Name"=>"Wild Roots Boulder Creek Grocery", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Willey Farms", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Windmill Farms", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Winn Dixie", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Winter Ridge Natural Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Withey's Health Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Woodman's", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"World Foods", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Wynn's Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Yoke's Fresh Market", "Planning Retailer"=>"All Other"},
          {"Retail Chain Name"=>"Zupan's Market", "Planning Retailer"=>"All Other"}
        ]

        def get_planning_retailer_lookup(retail_chain_name)
          retail_chain_name = retail_chain_name.try(:downcase).try(:strip)
          PLANNING_RETAILER_LOOKUP.each do |lookup|
            return lookup if lookup['Retail Chain Name'].try(:downcase) == retail_chain_name
          end

          {"Retail Chain Name"=>retail_chain_name, "Planning Retailer"=>"N/A in Planning Retailer Lookup"}
        end
      end
    end
  end
end
