module Mappers
  module Helpers
    module GlobalLookups
      module RetailChainNameLookup
        RETAIL_CHAIN_NAME_LOOOKUP = [
          {"Customer Chain ID"=>"A-1 NUTRITION *TRUCK*INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"AAS", "Retail Chain Name"=>"Alfalfas"},
          {"Customer Chain ID"=>"AB2", "Retail Chain Name"=>"Alexanders"},
          {"Customer Chain ID"=>"ABBY'S HEALTH FOOD *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"AFF", "Retail Chain Name"=>"Adams Fairacre Farm"},
          {"Customer Chain ID"=>"AG8", "Retail Chain Name"=>"Chucks Produce"},
          {"Customer Chain ID"=>"Ahold / Stop & Shop", "Retail Chain Name"=>"Ahold / Stop & Shop"},
          {"Customer Chain ID"=>"Akins Natural Foods", "Retail Chain Name"=>"Akins Natural Foods"},
          {"Customer Chain ID"=>"AKN", "Retail Chain Name"=>"Chamberlin's Marketplace"},
          {"Customer Chain ID"=>"ALAMEDA NATURAL KD (INFRA)", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"Albertson / Safeway", "Retail Chain Name"=>"Safeway / Albertsons"},
          {"Customer Chain ID"=>"Albertsons", "Retail Chain Name"=>"Safeway / Albertsons"},
          {"Customer Chain ID"=>"ALG", "Retail Chain Name"=>"Alameda Natural Grocery"},
          {"Customer Chain ID"=>"APPLE TREEE NATURAL FOODS", "Retail Chain Name"=>"Apple Tree Natural Foods"},
          {"Customer Chain ID"=>"ARC", "Retail Chain Name"=>"Harvest Market"},
          {"Customer Chain ID"=>"AS3", "Retail Chain Name"=>"Giunta's Meat Farms"},
          {"Customer Chain ID"=>"ATK", "Retail Chain Name"=>"Atkinson Market"},
          {"Customer Chain ID"=>"AWF", "Retail Chain Name"=>"Ada's Natural Market"},
          {"Customer Chain ID"=>"BALDUCCI'S  #117 RESTON", "Retail Chain Name"=>"Balducci's"},
          {"Customer Chain ID"=>"BALDUCCI'S 102 BETHESDA", "Retail Chain Name"=>"Balducci's"},
          {"Customer Chain ID"=>"BALDUCCI'S 103 ALEXANDRIA", "Retail Chain Name"=>"Balducci's"},
          {"Customer Chain ID"=>"BALDUCCI'S 116 MCLEAN", "Retail Chain Name"=>"Balducci's"},
          {"Customer Chain ID"=>"BALDUCCI'S 310 WESTPORT", "Retail Chain Name"=>"Balducci's"},
          {"Customer Chain ID"=>"BALDUCCI'S 311 GREENWICH", "Retail Chain Name"=>"Balducci's"},
          {"Customer Chain ID"=>"BALDUCCI'S 314 SCARSDALE", "Retail Chain Name"=>"Balducci's"},
          {"Customer Chain ID"=>"BALDUCCI'S 315 RYE BROOK", "Retail Chain Name"=>"Balducci's"},
          {"Customer Chain ID"=>"BALESMARKET PLACE CEDAR MILL", "Retail Chain Name"=>"Bales Marketplace"},
          {"Customer Chain ID"=>"BALESMARKET PLACE FARMINGTON", "Retail Chain Name"=>"Bales Marketplace"},
          {"Customer Chain ID"=>"BALLARD MARKET #211", "Retail Chain Name"=>"Ballard Market"},
          {"Customer Chain ID"=>"BAR", "Retail Chain Name"=>"Barons Market"},
          {"Customer Chain ID"=>"Bashas", "Retail Chain Name"=>"Bashas"},
          {"Customer Chain ID"=>"BASICFOOD LTD", "Retail Chain Name"=>"Basic Food Ltd"},
          {"Customer Chain ID"=>"BASILBANDWAGON CLINTON*INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BASILBANDWAGON NATURAL*INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BATHNATURAL MARKET INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BAYVIEW THRIFTWAY", "Retail Chain Name"=>"Thriftway"},
          {"Customer Chain ID"=>"BEACON NATURAL MARKET", "Retail Chain Name"=>"Beacon Natural Market"},
          {"Customer Chain ID"=>"BETTER HEALTH - PLYMOUTH INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BETTER HEALTH -ANN ARBOR INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BETTER HEALTH- BEVERLYHILLS", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BETTER HEALTH BLMFLD HILLS INF", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BETTER HEALTH -DEARBORN  INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BETTER HEALTH GROSSE PNT INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BETTER HEALTH -LIVONIAINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BETTER HEALTH STORE NOVI INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BETTER HEALTH-BELLEVILLE INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BETTER HEALTH-FRANDORINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BETTER HEALTH-SHELBY TWP INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BETTER HEALTH-SOUTHGATE INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BETTER HEALTH-W SAGINAW  INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BETTER HEATLH STRLNG HGTS INFR", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BFD", "Retail Chain Name"=>"Organic Basic Food"},
          {"Customer Chain ID"=>"BGY", "Retail Chain Name"=>"BIG Y"},
          {"Customer Chain ID"=>"BHS", "Retail Chain Name"=>"Better Health"},
          {"Customer Chain ID"=>"Big Y", "Retail Chain Name"=>"BIG Y"},
          {"Customer Chain ID"=>"BLOOMNATURALLY LLC \"INFRA\"", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"BLS", "Retail Chain Name"=>"Blossom on Lopez, Inc."},
          {"Customer Chain ID"=>"BONEY'S BAYSIDE MKT/GROCERY", "Retail Chain Name"=>"Boney's Bayside Market"},
          {"Customer Chain ID"=>"BRI", "Retail Chain Name"=>"Bristol Farms"},
          {"Customer Chain ID"=>"Bristol Farms", "Retail Chain Name"=>"Bristol Farms"},
          {"Customer Chain ID"=>"BRO", "Retail Chain Name"=>"Broulms"},
          {"Customer Chain ID"=>"Brookshire Grocery", "Retail Chain Name"=>"Brookshire Grocery"},
          {"Customer Chain ID"=>"BVG", "Retail Chain Name"=>"Berryvale Grocery"},
          {"Customer Chain ID"=>"BWF", "Retail Chain Name"=>"World Foods"},
          {"Customer Chain ID"=>"BWL", "Retail Chain Name"=>"Berkeley Bowl"},
          {"Customer Chain ID"=>"BYF", "Retail Chain Name"=>"BIG Y"},
          {"Customer Chain ID"=>"CAMBRIDGE NATURALS *INFRA* *", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"CAMPBELL'S NUTRITION *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"CAO", "Retail Chain Name"=>"California Organics"},
          {"Customer Chain ID"=>"CARDIFF SEASIDE MKT (RTB)", "Retail Chain Name"=>"Cardiff Seaside Market"},
          {"Customer Chain ID"=>"CASHWISE #3004", "Retail Chain Name"=>"Cashwise"},
          {"Customer Chain ID"=>"CASHWISE #3013", "Retail Chain Name"=>"Cashwise"},
          {"Customer Chain ID"=>"CASHWISE #3015", "Retail Chain Name"=>"Cashwise"},
          {"Customer Chain ID"=>"CASHWISE #3020", "Retail Chain Name"=>"Cashwise"},
          {"Customer Chain ID"=>"CASHWISE #3043#SV120439", "Retail Chain Name"=>"Cashwise"},
          {"Customer Chain ID"=>"CASHWISE #3044  SV#12-0123", "Retail Chain Name"=>"Cashwise"},
          {"Customer Chain ID"=>"CASHWISE #3045", "Retail Chain Name"=>"Cashwise"},
          {"Customer Chain ID"=>"CASHWISE #3050", "Retail Chain Name"=>"Cashwise"},
          {"Customer Chain ID"=>"CASHWISE JAMESTOWN #3049", "Retail Chain Name"=>"Cashwise"},
          {"Customer Chain ID"=>"CDF", "Retail Chain Name"=>"Crest Discount Foods"},
          {"Customer Chain ID"=>"CDS", "Retail Chain Name"=>"Cids Food Market"},
          {"Customer Chain ID"=>"CENTRAL MARKETS #212", "Retail Chain Name"=>"Central Market"},
          {"Customer Chain ID"=>"CENTRAL MARKETS #216", "Retail Chain Name"=>"Central Market"},
          {"Customer Chain ID"=>"CENTRAL MARKETS #217", "Retail Chain Name"=>"Central Market"},
          {"Customer Chain ID"=>"CFF", "Retail Chain Name"=>"Carnival Finer Foods"},
          {"Customer Chain ID"=>"CFM", "Retail Chain Name"=>"Community Market"},
          {"Customer Chain ID"=>"CGA", "Retail Chain Name"=>"NCG"},
          {"Customer Chain ID"=>"CHAMOMILLE NATURAL FDS*INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"CHESTERTOWN NATURAL FDS *INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"CHOICES NATURAL MARKETINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"CHS", "Retail Chain Name"=>"Coos Head Food Co-op"},
          {"Customer Chain ID"=>"CITYFEED AND SUPPLY *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"CLOVER'S NATURAL FDS SINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"CLOVER'S NATURAL FOODSINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"CMW", "Retail Chain Name"=>"Mississippi Market"},
          {"Customer Chain ID"=>"CNA", "Retail Chain Name"=>"Cannatas Family Mkt"},
          {"Customer Chain ID"=>"CNE", "Retail Chain Name"=>"Everman Natural Foods"},
          {"Customer Chain ID"=>"CNT", "Retail Chain Name"=>"Clark's Nutrition Center"},
          {"Customer Chain ID"=>"COA", "Retail Chain Name"=>"Country Aire Grocery"},
          {"Customer Chain ID"=>"COBORNS", "Retail Chain Name"=>"Coborns"},
          {"Customer Chain ID"=>"COBORNS #2019", "Retail Chain Name"=>"Coborns"},
          {"Customer Chain ID"=>"COBORNS #2022", "Retail Chain Name"=>"Coborns"},
          {"Customer Chain ID"=>"COBORNS #2023 CASHWISEFDS", "Retail Chain Name"=>"Coborns"},
          {"Customer Chain ID"=>"COBORNS #2027", "Retail Chain Name"=>"Coborns"},
          {"Customer Chain ID"=>"COBORNS #2031", "Retail Chain Name"=>"Coborns"},
          {"Customer Chain ID"=>"COBORNS #2032", "Retail Chain Name"=>"Coborns"},
          {"Customer Chain ID"=>"COBORNS #2033", "Retail Chain Name"=>"Coborns"},
          {"Customer Chain ID"=>"COBORNS #2035 SUPERSTORE", "Retail Chain Name"=>"Coborns"},
          {"Customer Chain ID"=>"COBORNS #2037", "Retail Chain Name"=>"Coborns"},
          {"Customer Chain ID"=>"COBORNS #2038 SUPERSTORE", "Retail Chain Name"=>"Coborns"},
          {"Customer Chain ID"=>"COBORNS #3009 CASHWISEFOODS", "Retail Chain Name"=>"Coborns"},
          {"Customer Chain ID"=>"COBORNS #3011 CASHWISEFOODS", "Retail Chain Name"=>"Coborns"},
          {"Customer Chain ID"=>"COMMUNITY GRDN MKT BERKL*INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"CORNUCOPIA FOODS *INFRA* MA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"CORNUCOPIA FOODS *INFRA* NY", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"CORNUCOPIA NATRL WLLNSS INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"CVN", "Retail Chain Name"=>"Country Village Nutrition"},
          {"Customer Chain ID"=>"DAHLIA & SAGE COMMUNITY MARKET", "Retail Chain Name"=>"Dahlia & Sage Community Market"},
          {"Customer Chain ID"=>"DAN", "Retail Chain Name"=>"Danimaxx"},
          {"Customer Chain ID"=>"DAVENPORT FARMS", "Retail Chain Name"=>"Davenport Farms"},
          {"Customer Chain ID"=>"DAVIDS NATURAL MARKETINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"DAWSON'S MARKET", "Retail Chain Name"=>"Dawson's Market"},
          {"Customer Chain ID"=>"DEBRA'S NATURAL GOURMET *INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"DEC", "Retail Chain Name"=>"Decicco Market"},
          {"Customer Chain ID"=>"DEL", "Retail Chain Name"=>"Fairfax IGA Market"},
          {"Customer Chain ID"=>"DELAND BAKERY&NAT MKT#93", "Retail Chain Name"=>"Deland Bakery & Natural Market"},
          {"Customer Chain ID"=>"Dierberg's", "Retail Chain Name"=>"Dierbergs"},
          {"Customer Chain ID"=>"DIX", "Retail Chain Name"=>"Dixie Nutrition"},
          {"Customer Chain ID"=>"DNF", "Retail Chain Name"=>"Deans Natural Food Market"},
          {"Customer Chain ID"=>"DOVER NATURAL FOODS", "Retail Chain Name"=>"Dover Natural Foods"},
          {"Customer Chain ID"=>"DOWNTO EARTH *INFRA*IN", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"DOWNTOWN GROCERY *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"DRA", "Retail Chain Name"=>"Draeger's"},
          {"Customer Chain ID"=>"DRIVER'S MARKET (INFRA)", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"DRM", "Retail Chain Name"=>"Drivers Market"},
          {"Customer Chain ID"=>"DRY", "Retail Chain Name"=>"Rainbow Foods"},
          {"Customer Chain ID"=>"DUCKWEED URBAN MARKET", "Retail Chain Name"=>"Duckweed Urban Market"},
          {"Customer Chain ID"=>"Earth Fare", "Retail Chain Name"=>"Earth Fare"},
          {"Customer Chain ID"=>"Earth Origins", "Retail Chain Name"=>"Earth Origins"},
          {"Customer Chain ID"=>"EARTHLIGHT NATURAL FOODS INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"EAST VILLAGE ORGANIC", "Retail Chain Name"=>"East Village Organic"},
          {"Customer Chain ID"=>"ECR", "Retail Chain Name"=>"Sweet Clover Market, Llc"},
          {"Customer Chain ID"=>"ED", "Retail Chain Name"=>"Elm Health"},
          {"Customer Chain ID"=>"EDI", "Retail Chain Name"=>"Just Local Food Coop"},
          {"Customer Chain ID"=>"EDWARDS MARKET LLC", "Retail Chain Name"=>"Edwards Market LLC"},
          {"Customer Chain ID"=>"EFA", "Retail Chain Name"=>"Earth Fare"},
          {"Customer Chain ID"=>"ELLWOOD THOMPSONS INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"EOM", "Retail Chain Name"=>"Earth Origins"},
          {"Customer Chain ID"=>"EUR", "Retail Chain Name"=>"Eureka Natural Foods"},
          {"Customer Chain ID"=>"EWN", "Retail Chain Name"=>"Erewhon"},
          {"Customer Chain ID"=>"FAN", "Retail Chain Name"=>"Fresh & Natural"},
          {"Customer Chain ID"=>"FDS", "Retail Chain Name"=>"Health Hut"},
          {"Customer Chain ID"=>"FEEL-RITE", "Retail Chain Name"=>"Feel-Rite"},
          {"Customer Chain ID"=>"FEELRITE FRESH MARKETINC", "Retail Chain Name"=>"Feel-Rite"},
          {"Customer Chain ID"=>"FFL", "Retail Chain Name"=>"Nugget Market"},
          {"Customer Chain ID"=>"FGS", "Retail Chain Name"=>"For Goodness Sake"},
          {"Customer Chain ID"=>"FIT-FOODS", "Retail Chain Name"=>"Fit-Foods"},
          {"Customer Chain ID"=>"FJM", "Retail Chain Name"=>"Farmer Joe`s"},
          {"Customer Chain ID"=>"FLS", "Retail Chain Name"=>"Sherms"},
          {"Customer Chain ID"=>"FOUNTAIN CITY HEALTH FOODS INC", "Retail Chain Name"=>"Fountain City Health Foods"},
          {"Customer Chain ID"=>"FOUR SEASONS MARKET LLC", "Retail Chain Name"=>"Four Seasons Market LLC"},
          {"Customer Chain ID"=>"FRAZIER FARMS-GROC/MONINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"FRAZIER FARMS-OCEANSIDE INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"Fresh Market", "Retail Chain Name"=>"The Fresh Market"},
          {"Customer Chain ID"=>"Fresh Thyme", "Retail Chain Name"=>"Fresh Thyme"},
          {"Customer Chain ID"=>"FRESHPLUS AUSTIN INC#1 INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"FRESHPLUS INC #2 INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"FREY'S BETTER FOODS *INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"FRF", "Retail Chain Name"=>"Whole Foods"},
          {"Customer Chain ID"=>"FW", "Retail Chain Name"=>"Foodworks II"},
          {"Customer Chain ID"=>"FWY", "Retail Chain Name"=>"Fairway"},
          {"Customer Chain ID"=>"G&R", "Retail Chain Name"=>"Grassroots Natural Market"},
          {"Customer Chain ID"=>"G2P", "Retail Chain Name"=>"Locale Market"},
          {"Customer Chain ID"=>"GARDEN HOME MARKET", "Retail Chain Name"=>"Garden Home Market"},
          {"Customer Chain ID"=>"GAW", "Retail Chain Name"=>"Green Acres"},
          {"Customer Chain ID"=>"Gelson's Markets", "Retail Chain Name"=>"Gelson's Markets"},
          {"Customer Chain ID"=>"GFS", "Retail Chain Name"=>"Good Food Store"},
          {"Customer Chain ID"=>"Giant Eagle", "Retail Chain Name"=>"Giant Eagle"},
          {"Customer Chain ID"=>"GOL", "Retail Chain Name"=>"Garden of Light"},
          {"Customer Chain ID"=>"GOOD SHEPERD HEALTH", "Retail Chain Name"=>"Good Shepherd Health"},
          {"Customer Chain ID"=>"GOODFOODS GROCERY 1/P*INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"GRANITE STATE NAT FOODS", "Retail Chain Name"=>"Granite State Natural Foods"},
          {"Customer Chain ID"=>"GRASS VALLEY", "Retail Chain Name"=>"SPD Market"},
          {"Customer Chain ID"=>"GRASSROOTS NATRL MKT II INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"Green Acres", "Retail Chain Name"=>"Green Acres"},
          {"Customer Chain ID"=>"GREENLIFE MARKET ANDVR INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"GREENLIFE MARKET BTLRINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"GREENLIFE MKT MRRSTWNINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"GREENS N GRAINS *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"GRM", "Retail Chain Name"=>"Grassroots Natural Market"},
          {"Customer Chain ID"=>"GROSVENOR MARKET", "Retail Chain Name"=>"Grosvenor Market"},
          {"Customer Chain ID"=>"GRS", "Retail Chain Name"=>"Graul's Market"},
          {"Customer Chain ID"=>"GUIDO'S FRESH MRKTPLACE *INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"GUIDO'S FRESH MRKTPLACE INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"GWM", "Retail Chain Name"=>"Gateway Market"},
          {"Customer Chain ID"=>"GZG", "Retail Chain Name"=>"Green Zebra Grocery"},
          {"Customer Chain ID"=>"H.E.B#708", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B#709", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B.  #622", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B.  #623", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B.  #705", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. # 019 LYTLE", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. # 039 BELTON", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. # 621 BOERNE", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. # 630 ALABAMA &DUNLAVY", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. # 639", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. # 660", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. # 675", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. # 686", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. # 696", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. # 698", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #016 BURLESON", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #020", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #024", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #028", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #029", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #031", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #034", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #045 (DRY)", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #048", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #068", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #070", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #074", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #089", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #096", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #099", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #102", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #109", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #110", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #164", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #202", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #218", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #225", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #227", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #265", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #269", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #372", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #373", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #382", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #385", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #387", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #388", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #404", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #415", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #425", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #426", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #428", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #444", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #451", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #463", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #474", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #476", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #479", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #480", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #487", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #492", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #495", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #497", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #498", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #543", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #558", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #561", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #563", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #566", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #567", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #579", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #580", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #582", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #589", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #590", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #594", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #599", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #610", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #611", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #615", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #619 COLLEGE STATION", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #627 SUGARLAND", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #656  - CYPRESS", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #668", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #687", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #694", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #697", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #706 EDC", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #713", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #714", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #715", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #716", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #717", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #720", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #722", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #724", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #725", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #727", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #732", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #733", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #735", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #736", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #737", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #738", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #741", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #742", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #746", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. #748", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. PLUS #014", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. PLUS #057", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. PLUS #063", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. PLUS #069", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. PLUS #085", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. PLUS #092", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. PLUS #094", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. PLUS #108", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. PLUS #591", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. PLUS #592", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B. PLUS #596", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B.# 631 GRANBURY", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B.# 638 WOODLANDS4", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"H.E.B.#673", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"Harmon's", "Retail Chain Name"=>"Harmon's"},
          {"Customer Chain ID"=>"HARVEST MARKET *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"HARVEST MENDOSA (RTB)", "Retail Chain Name"=>"Harvest Market"},
          {"Customer Chain ID"=>"HARVEST MKT GROC(RTB)", "Retail Chain Name"=>"Harvest Market"},
          {"Customer Chain ID"=>"HEALTH FOOD CENTER", "Retail Chain Name"=>"Health Food Center"},
          {"Customer Chain ID"=>"HEALTHFAIR *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"HEALTHY FOODS PLUS", "Retail Chain Name"=>"Healthy Foods Plus"},
          {"Customer Chain ID"=>"HEALTHY HABITS LLC INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"HEALTHY LIVING ORG MKT*INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"HEALTHY THYMES MARKET*INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"HEALTHYWAY OF SOUTHERN NE", "Retail Chain Name"=>"Healthway of Southern NE"},
          {"Customer Chain ID"=>"HEB", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"HEB #659 AUSTIN", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"HEB #752", "Retail Chain Name"=>"HEB"},
          {"Customer Chain ID"=>"HENDERSONVILLE PRODUCE", "Retail Chain Name"=>"Hendersonville Produce"},
          {"Customer Chain ID"=>"HGT", "Retail Chain Name"=>"Haight Street Market"},
          {"Customer Chain ID"=>"HLS", "Retail Chain Name"=>"Healthy Living"},
          {"Customer Chain ID"=>"HML", "Retail Chain Name"=>"Homeland"},
          {"Customer Chain ID"=>"HMU", "Retail Chain Name"=>"Honest Green Market LLC"},
          {"Customer Chain ID"=>"HOP", "Retail Chain Name"=>"Mt. Hope"},
          {"Customer Chain ID"=>"HSN", "Retail Chain Name"=>"Key Food"},
          {"Customer Chain ID"=>"HSU &CO., INC. #2", "Retail Chain Name"=>"HSU & Co"},
          {"Customer Chain ID"=>"HSU &CO., INC. #4", "Retail Chain Name"=>"HSU & Co"},
          {"Customer Chain ID"=>"HTH", "Retail Chain Name"=>"Health Nuts"},
          {"Customer Chain ID"=>"HVT", "Retail Chain Name"=>"Harvest Health"},
          {"Customer Chain ID"=>"HYS", "Retail Chain Name"=>"Hollywood Supermarket"},
          {"Customer Chain ID"=>"IC2", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"IC4", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"IF2", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"IF3", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"IF5", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"IFN", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"IM2", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"INF", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"INI", "Retail Chain Name"=>"Pats Marketplace"},
          {"Customer Chain ID"=>"INR", "Retail Chain Name"=>"Nature's Green Grocer"},
          {"Customer Chain ID"=>"IR2", "Retail Chain Name"=>"Native Sun"},
          {"Customer Chain ID"=>"ISN", "Retail Chain Name"=>"Island Naturals"},
          {"Customer Chain ID"=>"ITS ONLY NATURAL MKT LLC*INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"JANSSEN'S MARKET LLC", "Retail Chain Name"=>"Janssen's Market LLC"},
          {"Customer Chain ID"=>"JIMBOS NAT #2-DELMAR/GRC INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"JIMBO'S NAT-4S/GROCERYINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"JIMBO'S NAT-ESC/GROC INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"JIMBOS NAT-HRTN PLZ-GROC INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"JIMBO'S NATURALLY-GROCINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"JMB", "Retail Chain Name"=>"Jimbos"},
          {"Customer Chain ID"=>"JOHNSON COMPOUNDING CENTR", "Retail Chain Name"=>"Johnson Compounding Center"},
          {"Customer Chain ID"=>"JWG", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"JWG -DRY GROCERY INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"KANKAKEE NATURAL FOODSINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"KCN", "Retail Chain Name"=>"Tapps Supermarket"},
          {"Customer Chain ID"=>"KeHE", "Retail Chain Name"=>"KeHE"},
          {"Customer Chain ID"=>"KEN", "Retail Chain Name"=>"Ken's Market"},
          {"Customer Chain ID"=>"KETTLE", "Retail Chain Name"=>"Kettle and Fire, Inc."},
          {"Customer Chain ID"=>"KIMBERTON WHLFDS CLLGVLL INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"KIMBERTON WHLFDS MLVRNINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"KIMBERTON WHOLE FDS WHINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"KIMBERTON WHOLE FDS/DTINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"KIMBERTON WHOLE FDS/DVINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"KIMBERTON WHOLE FDS/KIMB INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"KIMBERTON WHOLE FDS/OTINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"KIMBERTON WHOLE FDS/OTTS INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"KING SOOPERS 620", "Retail Chain Name"=>"Safeway / Albertsons"},
          {"Customer Chain ID"=>"Kings", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MAREKT # 39", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 12", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 21", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 28", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 29", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 35", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 37", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 38", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 40", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 41", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 42", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 43", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 44", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 49", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 51", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 56", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 57", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 58", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 59", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 60", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 61", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 64", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 66", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 67", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KINGSSUPER MARKET # 68", "Retail Chain Name"=>"Kings Super Market"},
          {"Customer Chain ID"=>"KOW", "Retail Chain Name"=>"Kowalski"},
          {"Customer Chain ID"=>"Kowalski", "Retail Chain Name"=>"Kowalski"},
          {"Customer Chain ID"=>"Kroger", "Retail Chain Name"=>"Kroger"},
          {"Customer Chain ID"=>"LAMBS FRESH MARKET", "Retail Chain Name"=>"Lambs Fresh Market"},
          {"Customer Chain ID"=>"Lassens", "Retail Chain Name"=>"Lassen's"},
          {"Customer Chain ID"=>"LASSEN'S BAKERSFIELD", "Retail Chain Name"=>"Lassen's"},
          {"Customer Chain ID"=>"LASSEN'S ECHO PARK", "Retail Chain Name"=>"Lassen's"},
          {"Customer Chain ID"=>"LASSEN'S FRESNO", "Retail Chain Name"=>"Lassen's"},
          {"Customer Chain ID"=>"LASSEN'S LA BREA", "Retail Chain Name"=>"Lassen's"},
          {"Customer Chain ID"=>"LASSEN'S LOS FELIZ", "Retail Chain Name"=>"Lassen's"},
          {"Customer Chain ID"=>"LASSEN'S OXNARD", "Retail Chain Name"=>"Lassen's"},
          {"Customer Chain ID"=>"LASSEN'S SAN LUIS OBISPO", "Retail Chain Name"=>"Lassen's"},
          {"Customer Chain ID"=>"LASSEN'S SANTA BARBARA", "Retail Chain Name"=>"Lassen's"},
          {"Customer Chain ID"=>"LASSEN'S SANTA MARIA", "Retail Chain Name"=>"Lassen's"},
          {"Customer Chain ID"=>"LASSEN'S SIMI VALLEY", "Retail Chain Name"=>"Lassen's"},
          {"Customer Chain ID"=>"LASSEN'S THOUSAND OAKS", "Retail Chain Name"=>"Lassen's"},
          {"Customer Chain ID"=>"LASSEN'S VENTURA", "Retail Chain Name"=>"Lassen's"},
          {"Customer Chain ID"=>"LAZ", "Retail Chain Name"=>"Lazy Acres"},
          {"Customer Chain ID"=>"Lazy Acres", "Retail Chain Name"=>"Lazy Acres"},
          {"Customer Chain ID"=>"LEG UP FRMRS MKT/GROCERY INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"LEMONSTREET MARKET INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"LMK", "Retail Chain Name"=>"LMK Grocery"},
          {"Customer Chain ID"=>"LOCALE MARKET", "Retail Chain Name"=>"Locale Market"},
          {"Customer Chain ID"=>"LORI'S NATURAL FOODS CTR INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"LOVEY'S NATURAL FDS&CAFE*INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"LSO", "Retail Chain Name"=>"Lifesource Natural Foods"},
          {"Customer Chain ID"=>"MAGGIE'S MARKET *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"MAMAJEANS NAT FDS MKT#2INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"MAMAJEANS NAT FDS MKT#3INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"MAMAJEAN'S NATURAL MRKT INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"MAR", "Retail Chain Name"=>"Marlene's"},
          {"Customer Chain ID"=>"MARDIGRAS ZONE LLC", "Retail Chain Name"=>"Mardi Gras Zone"},
          {"Customer Chain ID"=>"MARKETPLACE NATL 2581", "Retail Chain Name"=>"Marketplace Natural"},
          {"Customer Chain ID"=>"MARKETPLACE NATL 2583", "Retail Chain Name"=>"Marketplace Natural"},
          {"Customer Chain ID"=>"MARLIN MARKET", "Retail Chain Name"=>"Marlin Market"},
          {"Customer Chain ID"=>"MARTINDALES NATURAL FD*INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"MAZ", "Retail Chain Name"=>"Manzanita Fresh Food"},
          {"Customer Chain ID"=>"MDI", "Retail Chain Name"=>"Merchant Distributors, Inc."},
          {"Customer Chain ID"=>"Meijer", "Retail Chain Name"=>"Meijer"},
          {"Customer Chain ID"=>"MFM", "Retail Chain Name"=>"Meyers Falls Market"},
          {"Customer Chain ID"=>"MIS", "Retail Chain Name"=>"Missoula Fresh Market"},
          {"Customer Chain ID"=>"MISSION NUTRITION", "Retail Chain Name"=>"Mission Nutrition"},
          {"Customer Chain ID"=>"MLR", "Retail Chain Name"=>"MILLER'S NATURAL FOODS"},
          {"Customer Chain ID"=>"MOC", "Retail Chain Name"=>"Market of Choice"},
          {"Customer Chain ID"=>"MOL", "Retail Chain Name"=>"Mollie Stones"},
          {"Customer Chain ID"=>"Mollie Stone's", "Retail Chain Name"=>"Mollie Stones"},
          {"Customer Chain ID"=>"MOR", "Retail Chain Name"=>"Morton William"},
          {"Customer Chain ID"=>"MORNING GLORY NAT FDS*INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"MOTHER EARTH  *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"MOTHER'S MKT AH/GROC", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT BREA-GROC", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT BREA-GROCPROMO", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT CM/GROCERY PROMO", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT CM/GROCERY#3", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT HB/GROCERY", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT HB/GROCERY PROMO", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT IR/GROC", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT IR/GROC PROMO", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT LW/GROCERY-REG", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT LW/GROC-PROMO", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT MB/GROCERY", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT SA/GROC", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT SA/GROC PROMO", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKT SH/GROCERY", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MOTHER'S MKTMB/GROCERY", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MTR", "Retail Chain Name"=>"Mother's Market"},
          {"Customer Chain ID"=>"MUR", "Retail Chain Name"=>"Murphy's"},
          {"Customer Chain ID"=>"MUS", "Retail Chain Name"=>"Mustard Seed"},
          {"Customer Chain ID"=>"MVF", "Retail Chain Name"=>"Mountain Valley Foods"},
          {"Customer Chain ID"=>"NAM", "Retail Chain Name"=>"Newport Avenue Market"},
          {"Customer Chain ID"=>"NAP", "Retail Chain Name"=>"Natural Pantry Dry"},
          {"Customer Chain ID"=>"NAT", "Retail Chain Name"=>"Natural Frontier"},
          {"Customer Chain ID"=>"NATURAL CHOICES *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NATURAL FOOD PLUS", "Retail Chain Name"=>"Natural Food Plus"},
          {"Customer Chain ID"=>"NATURAL FOODS MARKET *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"Natural Grocers (NGVC)", "Retail Chain Name"=>"Natural Grocers (NGVC)"},
          {"Customer Chain ID"=>"NATURAL PROVISIONS INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NATURES FOOD PATCH *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NATURES FOOD PATCH IIINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NATURE'S OWN HLTH FOODS INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NATURE'S PANTRY INFRAPA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NATURES TEMPTATIONS  INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NATURE'S WAY FD OUTLET*INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NATURE'S WONDERS INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NCG", "Retail Chain Name"=>"NCG"},
          {"Customer Chain ID"=>"NEA", "Retail Chain Name"=>"New Earth Market"},
          {"Customer Chain ID"=>"NEM", "Retail Chain Name"=>"County Market"},
          {"Customer Chain ID"=>"NEO", "Retail Chain Name"=>"County Market"},
          {"Customer Chain ID"=>"NEW BRIDGE ORGANIC MARKET", "Retail Chain Name"=>"New Bridge Organic Market"},
          {"Customer Chain ID"=>"NEW EARTH CHICO/REFRIGINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NEW EARTH MARKET(INFRA)", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NEW FRONTIER SOLV/GROC(INFRA)", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NEW LEAF APTOS GROCERY", "Retail Chain Name"=>"New Leaf"},
          {"Customer Chain ID"=>"NEW MORNING COUNTRY STR *INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NEW MORNING PROMO INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NGC BERKELEY - GROCERYINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NGS", "Retail Chain Name"=>"Nature's Goods"},
          {"Customer Chain ID"=>"NLC", "Retail Chain Name"=>"Natural Living Center"},
          {"Customer Chain ID"=>"NLI", "Retail Chain Name"=>"Wild Roots Boulder Creek Grocery"},
          {"Customer Chain ID"=>"NMN", "Retail Chain Name"=>"New Moon Natural Foods"},
          {"Customer Chain ID"=>"NMP", "Retail Chain Name"=>"Garden Gourmet Market"},
          {"Customer Chain ID"=>"NOR", "Retail Chain Name"=>"Nori's Village Market"},
          {"Customer Chain ID"=>"NRG", "Retail Chain Name"=>"Earth Origins"},
          {"Customer Chain ID"=>"NSM ARBOR LODGE #6 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM CEDAR HILLS #8 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM CONCORDIA #4 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM FISHER'S LANDING #12 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM GRANT PARK #15 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM HAPPY VALLEY #9 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM HAWTHORNE #10 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM MOUNTAIN PARK #7 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM NYBERG RIVERS #14GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM ORENCO STATION #3GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM PROGRESS RIDGE #11GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM RALEIGH HILLS #1 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM SELLWOOD #2 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM SEVEN CORNERS #5 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM SLABTOWN #16 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM UNIVERSITY PARK #18 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM WILLIAMS #13 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSM WOODSTOCK #17 GG", "Retail Chain Name"=>"New Seasons Market"},
          {"Customer Chain ID"=>"NSW", "Retail Chain Name"=>"Natural Way Health Foods"},
          {"Customer Chain ID"=>"NUTRITION S'MART PINEINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"NWG", "Retail Chain Name"=>"Thriftway"},
          {"Customer Chain ID"=>"OAK", "Retail Chain Name"=>"Palace Market"},
          {"Customer Chain ID"=>"ODG", "Retail Chain Name"=>"Love Whole Foods"},
          {"Customer Chain ID"=>"OGA", "Retail Chain Name"=>"Organica"},
          {"Customer Chain ID"=>"OLI", "Retail Chain Name"=>"Olivers Market"},
          {"Customer Chain ID"=>"OLYMPIA HEALTH FD. CTR.", "Retail Chain Name"=>"Olympia Health Food Center"},
          {"Customer Chain ID"=>"ONF", "Retail Chain Name"=>"Oregon Natural Foods"},
          {"Customer Chain ID"=>"ORGANIC FD DEPOT GRANBY *INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"ORGANIC FOOD DEPOT *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"ORGANIC MARKETPLACE INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"ORGANNONS NATURAL MARKET*INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"PALACE MARKET (RTB)", "Retail Chain Name"=>"Palace Market"},
          {"Customer Chain ID"=>"PALISADES MARKET", "Retail Chain Name"=>"Palisades Market"},
          {"Customer Chain ID"=>"PIAZZA'S-PA-GROC (RTB)", "Retail Chain Name"=>"Piazza's Fine Foods"},
          {"Customer Chain ID"=>"PIAZZA'S-SM-GROC (RTB)", "Retail Chain Name"=>"Piazza's Fine Foods"},
          {"Customer Chain ID"=>"PIL", "Retail Chain Name"=>"Pilgrms Nutrition"},
          {"Customer Chain ID"=>"PLM", "Retail Chain Name"=>"Plum Market"},
          {"Customer Chain ID"=>"POLSON'S", "Retail Chain Name"=>"Polson's"},
          {"Customer Chain ID"=>"PSC", "Retail Chain Name"=>"Park Slop Co-op"},
          {"Customer Chain ID"=>"Publix", "Retail Chain Name"=>"Publix"},
          {"Customer Chain ID"=>"RAINBOW ACRES 1/REG (INFRA)", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"RAINBOW BLOSSOM #5 GARDN*INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"RAINBOW BLOSSOM ALBANY*INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"RAINBOW BLOSSOM LEX  *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"RAINBOW BLOSSOM SHELB*INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"RAISIN RACK WESTERVILLE(PARENT", "Retail Chain Name"=>"Raisin Rack"},
          {"Customer Chain ID"=>"Raleys", "Retail Chain Name"=>"Raleys"},
          {"Customer Chain ID"=>"RAMONA FAMILY NATURALSINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"RBG", "Retail Chain Name"=>"Royal Blue Grocery"},
          {"Customer Chain ID"=>"Reasors", "Retail Chain Name"=>"Reasors"},
          {"Customer Chain ID"=>"REBECCA'S NATURAL FOODINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"RISING TIDE NAT FDS INC *INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"RIVER WARDS LLC", "Retail Chain Name"=>"River Wards LLC"},
          {"Customer Chain ID"=>"Rollin Oats Market & Cafe", "Retail Chain Name"=>"Rollin' Oats Market"},
          {"Customer Chain ID"=>"ROM", "Retail Chain Name"=>"Rollin' Oats Market"},
          {"Customer Chain ID"=>"ROOTSNAT FOODS LMNSTRINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"ROSEWOOD MARKET*INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"Roundy's", "Retail Chain Name"=>"Roundy's"},
          {"Customer Chain ID"=>"ROX", "Retail Chain Name"=>"Roxy's"},
          {"Customer Chain ID"=>"ROYALRIVER NATURAL FDS *INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"RTB", "Retail Chain Name"=>"Harvest Market"},
          {"Customer Chain ID"=>"RTH", "Retail Chain Name"=>"Roths Market"},
          {"Customer Chain ID"=>"RV2", "Retail Chain Name"=>"Jericho Market"},
          {"Customer Chain ID"=>"Safeway", "Retail Chain Name"=>"Safeway / Albertsons"},
          {"Customer Chain ID"=>"Safeway / Albertsons", "Retail Chain Name"=>"Safeway / Albertsons"},
          {"Customer Chain ID"=>"SCA", "Retail Chain Name"=>"CA Independent Natural Grocers"},
          {"Customer Chain ID"=>"SEVEN GRAINS NATURAL", "Retail Chain Name"=>"Seven Grains Natural"},
          {"Customer Chain ID"=>"SFH", "Retail Chain Name"=>"Frazier Farms"},
          {"Customer Chain ID"=>"SFM", "Retail Chain Name"=>"Sprouts"},
          {"Customer Chain ID"=>"SHI", "Retail Chain Name"=>"HI Independent Natural Grocers"},
          {"Customer Chain ID"=>"SHL", "Retail Chain Name"=>"Sunshine Health Foods"},
          {"Customer Chain ID"=>"SKOGENS", "Retail Chain Name"=>"Skogens"},
          {"Customer Chain ID"=>"SLA", "Retail Chain Name"=>"LA Independent Natural Grocers"},
          {"Customer Chain ID"=>"SMP", "Retail Chain Name"=>"Samples - UNFI"},
          {"Customer Chain ID"=>"SMT", "Retail Chain Name"=>"Withey's Health Foods"},
          {"Customer Chain ID"=>"SNK", "Retail Chain Name"=>"Shop-N-Kart"},
          {"Customer Chain ID"=>"SNM", "Retail Chain Name"=>"NM Independent Natural Grocers"},
          {"Customer Chain ID"=>"SOF", "Retail Chain Name"=>"Super 1 Foods"},
          {"Customer Chain ID"=>"SOHO ORGANIC MARKET", "Retail Chain Name"=>"SOHO Organic Market"},
          {"Customer Chain ID"=>"SOL", "Retail Chain Name"=>"Staff of Life"},
          {"Customer Chain ID"=>"SONNEWALD NATURAL FOODS INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"SOR", "Retail Chain Name"=>"OR Independent Natural Grocers"},
          {"Customer Chain ID"=>"SOUTHTOWN HEALTH FOODS(3)", "Retail Chain Name"=>"Southtown Health Foods"},
          {"Customer Chain ID"=>"SPICE N NICE", "Retail Chain Name"=>"Spice n Nice"},
          {"Customer Chain ID"=>"Sprouts", "Retail Chain Name"=>"Sprouts"},
          {"Customer Chain ID"=>"SPROUTS 427 SN LUS O GROC ST9", "Retail Chain Name"=>"Sprouts"},
          {"Customer Chain ID"=>"SPROUTS 43 SGNL BTE GROC ST 10", "Retail Chain Name"=>"Sprouts"},
          {"Customer Chain ID"=>"SPROUTS 433 CPTL EXY GROC ST10", "Retail Chain Name"=>"Sprouts"},
          {"Customer Chain ID"=>"SPROUTS 455 LYNNWOOD GROC ST10", "Retail Chain Name"=>"Sprouts"},
          {"Customer Chain ID"=>"SPROUTS 559 ALTA GROCST 5", "Retail Chain Name"=>"Sprouts"},
          {"Customer Chain ID"=>"SPROUTS 615 NAPLES GROC ST 9", "Retail Chain Name"=>"Sprouts"},
          {"Customer Chain ID"=>"SPROUTS 620 WELLGTN GROC ST 10", "Retail Chain Name"=>"Sprouts"},
          {"Customer Chain ID"=>"SPROUTS 945 MRLN CSNGGROC ST9", "Retail Chain Name"=>"Sprouts"},
          {"Customer Chain ID"=>"SRC", "Retail Chain Name"=>"Sebastopol Community Market"},
          {"Customer Chain ID"=>"STADIUM THRIFTWAY", "Retail Chain Name"=>"Thriftway"},
          {"Customer Chain ID"=>"STO", "Retail Chain Name"=>"The Store"},
          {"Customer Chain ID"=>"STREETS MARKET", "Retail Chain Name"=>"Streets Market"},
          {"Customer Chain ID"=>"STREETS MARKET M STREET", "Retail Chain Name"=>"Streets Market"},
          {"Customer Chain ID"=>"STS", "Retail Chain Name"=>"Calvert Retail"},
          {"Customer Chain ID"=>"SUN", "Retail Chain Name"=>"Country Sun"},
          {"Customer Chain ID"=>"SUNFLOWER NATURAL FOODS *INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"SUNFLOWER SHOPPE COL/REFRIG", "Retail Chain Name"=>"Sunflower Shoppe"},
          {"Customer Chain ID"=>"SUNFLOWER SHOPPE FT/HBC", "Retail Chain Name"=>"Sunflower Shoppe"},
          {"Customer Chain ID"=>"SUNSPOT NATURAL MARKETINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"SUNSPOT NATURAL MKT #2INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"SUZANNE'S NATURAL FOODS  INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"SWA", "Retail Chain Name"=>"WA Independent Natural Grocers"},
          {"Customer Chain ID"=>"TAILOR MADE NUTRITION", "Retail Chain Name"=>"Tailor Made Nutrition"},
          {"Customer Chain ID"=>"TFM", "Retail Chain Name"=>"The Fresh Market"},
          {"Customer Chain ID"=>"The Fresh Market", "Retail Chain Name"=>"The Fresh Market"},
          {"Customer Chain ID"=>"THE GOOD SEED NAT FD MRK INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"THE GREEN GROCER INC*INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"THE LOCAL FOOD MARKETINFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"THE MARKET ON MARKET INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"THE TRUCK PATCH #1 INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"THE TRUCK PATCH 2-JNSBRO INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"THE WHOLE WHEATERY KD(INFRA)", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"THE WHOLE WHEATERY-SPEC(INFRA)", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"TIC", "Retail Chain Name"=>"Ticonderoga Natural Foods"},
          {"Customer Chain ID"=>"Town & Country", "Retail Chain Name"=>"Town & Country Markets"},
          {"Customer Chain ID"=>"TOWN& COUNTRY MARKET#208", "Retail Chain Name"=>"Town & Country Markets"},
          {"Customer Chain ID"=>"TOWN& COUNTRY MARKET#215", "Retail Chain Name"=>"Town & Country Markets"},
          {"Customer Chain ID"=>"UNCLEDEAN'S GOOD GROCER INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"UNFI East", "Retail Chain Name"=>"UNFI East"},
          {"Customer Chain ID"=>"UNFI West", "Retail Chain Name"=>"UNFI West"},
          {"Customer Chain ID"=>"United", "Retail Chain Name"=>"Safeway / Albertsons"},
          {"Customer Chain ID"=>"URM", "Retail Chain Name"=>"URM"},
          {"Customer Chain ID"=>"VILLAGE MARKET", "Retail Chain Name"=>"Village Market"},
          {"Customer Chain ID"=>"VIT", "Retail Chain Name"=>"Natural Grocers (NGVC)"},
          {"Customer Chain ID"=>"VITALITY & HEALTH", "Retail Chain Name"=>"Vitality & Health"},
          {"Customer Chain ID"=>"VITAMINS PLUS #273-WACO", "Retail Chain Name"=>"Vitamins Plus"},
          {"Customer Chain ID"=>"VLG", "Retail Chain Name"=>"Village Market"},
          {"Customer Chain ID"=>"Wakefern", "Retail Chain Name"=>"Wakefern"},
          {"Customer Chain ID"=>"WARDSSUPERMARKET INC", "Retail Chain Name"=>"Wards Supermarket"},
          {"Customer Chain ID"=>"Wegman's", "Retail Chain Name"=>"Wegmans"},
          {"Customer Chain ID"=>"Wegmans", "Retail Chain Name"=>"Wegmans"},
          {"Customer Chain ID"=>"WESTERN MARKET", "Retail Chain Name"=>"Western Market"},
          {"Customer Chain ID"=>"WESTSIDE MARKET", "Retail Chain Name"=>"Westside Market"},
          {"Customer Chain ID"=>"WF3", "Retail Chain Name"=>"Whole Foods"},
          {"Customer Chain ID"=>"WFM", "Retail Chain Name"=>"Whole Foods"},
          {"Customer Chain ID"=>"WGE", "Retail Chain Name"=>"Wegmans"},
          {"Customer Chain ID"=>"WGM", "Retail Chain Name"=>"Wegmans"},
          {"Customer Chain ID"=>"Whole Foods", "Retail Chain Name"=>"Whole Foods"},
          {"Customer Chain ID"=>"WHOLEEARTH *INFRA*", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"WILDBERRIES MARKETPLACE INFRA", "Retail Chain Name"=>"INFRA"},
          {"Customer Chain ID"=>"WILLEY FARMS GALENA", "Retail Chain Name"=>"Willey Farms"},
          {"Customer Chain ID"=>"WINDMILL FARMS-GROCERY", "Retail Chain Name"=>"Windmill Farms"},
          {"Customer Chain ID"=>"WINDMILL FARMS-GROCERY/SUNDAY", "Retail Chain Name"=>"Windmill Farms"},
          {"Customer Chain ID"=>"Winn Dixie", "Retail Chain Name"=>"Winn Dixie"},
          {"Customer Chain ID"=>"WLT", "Retail Chain Name"=>"Wealth of Health"},
          {"Customer Chain ID"=>"WMW", "Retail Chain Name"=>"Whole Foods"},
          {"Customer Chain ID"=>"WNE", "Retail Chain Name"=>"Whole Foods"},
          {"Customer Chain ID"=>"WOODMAN'S #24 NON SERV", "Retail Chain Name"=>"Woodman's"},
          {"Customer Chain ID"=>"WOODMAN'S #30", "Retail Chain Name"=>"Woodman's"},
          {"Customer Chain ID"=>"WOODMAN'S #41 NON SERV", "Retail Chain Name"=>"Woodman's"},
          {"Customer Chain ID"=>"WRF", "Retail Chain Name"=>"Winter Ridge Natural Foods"},
          {"Customer Chain ID"=>"WSO", "Retail Chain Name"=>"Whole Foods"},
          {"Customer Chain ID"=>"WYS", "Retail Chain Name"=>"Wynn's Market"},
          {"Customer Chain ID"=>"YOK", "Retail Chain Name"=>"Yoke's Fresh Market"},
          {"Customer Chain ID"=>"Yoke's Fresh Market", "Retail Chain Name"=>"Yoke's Fresh Market"},
          {"Customer Chain ID"=>"ZUPAN'S MARKET #633", "Retail Chain Name"=>"Zupan's Market"},
          {"Customer Chain ID"=>"ZUPAN'S MARKET #640", "Retail Chain Name"=>"Zupan's Market"},
          {"Customer Chain ID"=>"ZUPAN'S MARKET #642", "Retail Chain Name"=>"Zupan's Market"}
        ]

        def get_retail_chain_name_lookup(customer_chain_id)
          RETAIL_CHAIN_NAME_LOOOKUP.each do |lookup|
            return lookup if lookup['Customer Chain ID'] == customer_chain_id
          end
        end
      end
    end
  end
end
